import Link from 'next/link'

export const metadata = { title: 'Terms of Service — PropertyState AI' }

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '#EEF2FF' }}>
      <header className="border-b" style={{ backgroundColor: '#0A1628', borderColor: 'rgba(212,175,55,0.4)' }}>
        <div className="max-w-3xl mx-auto px-6 py-4">
          <Link href="/" className="text-sm font-semibold" style={{ color: '#D4AF37' }}>← PropertyState AI</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12" style={{ color: '#0D1F3C' }}>
        <h1 className="text-3xl font-black mb-2">Terms of Service</h1>
        <p className="text-sm mb-8" style={{ color: '#2952A3' }}>Last updated: 2026-05-23</p>

        <div className="rounded-xl p-4 mb-6 text-sm" style={{ backgroundColor: '#FEF3C7', border: '1px solid #F59E0B', color: '#92400E' }}>
          <strong>This is a template.</strong> Replace with terms reviewed by a lawyer in your jurisdiction before going to production.
        </div>

        <Section title="1. Not financial advice">
          <p>PropertyState AI generates <strong>informational estimates</strong> only. Nothing the service produces is financial,
          tax, legal, or investment advice. Always consult licensed professionals (mortgage broker, accountant, quantity
          surveyor, conveyancer, financial adviser) before making any property investment decision.</p>
        </Section>

        <Section title="2. Estimates only">
          <p>All numbers — yield, cashflow, ROI, growth, tax benefit, recommended offer — are AI-generated estimates based on
          the inputs you provide and general market heuristics. They are not guarantees and may be materially wrong.</p>
        </Section>

        <Section title="3. Acceptable use">
          <ul>
            <li>One account per person.</li>
            <li>Do not abuse the service (no scraping, no automated mass-querying outside the published API).</li>
            <li>Do not submit property data you don&apos;t have a legitimate interest in analysing.</li>
          </ul>
        </Section>

        <Section title="4. Plan limits">
          <p>Your plan has monthly token + analysis caps. Once exceeded, analyses will be blocked until the next calendar
          month or until you upgrade.</p>
        </Section>

        <Section title="5. Liability">
          <p>To the maximum extent permitted by law, we are not liable for any losses arising from decisions made on the
          basis of reports generated by this service. Use at your own risk.</p>
        </Section>

        <Section title="6. Termination">
          <p>We may suspend accounts that violate these terms. You may delete your account at any time.</p>
        </Section>

        <Section title="7. Changes">
          <p>We may update these terms. Material changes will be notified by email (if you have an account) before they take effect.</p>
        </Section>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-lg font-bold mb-2" style={{ color: '#0D1F3C' }}>{title}</h2>
      <div style={{ color: '#0D1F3C' }}>{children}</div>
    </div>
  )
}
